# Generated by Django 2.2.2 on 2019-06-10 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenttemp',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='currenttemp',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currenttemp',
            name='text',
            field=models.TextField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='currenttemp',
            name='title',
            field=models.CharField(default='dedault temp', max_length=200),
        ),
    ]
