# Generated by Django 2.2.2 on 2019-06-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceapp', '0003_auto_20190610_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenttemp',
            name='temp',
            field=models.IntegerField(null=True),
        ),
    ]
