# Generated by Django 2.2.2 on 2019-06-10 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceapp', '0004_currenttemp_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currenttemp',
            old_name='created_date',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='currenttemp',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='currenttemp',
            name='text',
        ),
        migrations.RemoveField(
            model_name='currenttemp',
            name='title',
        ),
    ]
