# Generated by Django 2.2.2 on 2019-06-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceapp', '0005_auto_20190610_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp2', models.IntegerField(null=True)),
                ('temp3', models.IntegerField(null=True)),
            ],
        ),
    ]
