# Generated by Django 2.2.2 on 2019-06-10 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceapp', '0006_returnvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnvalue',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
