# Generated by Django 2.2.2 on 2019-06-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceapp', '0007_returnvalue_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnValue',
        ),
    ]
