# Generated by Django 2.2.2 on 2019-06-10 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interfaceapp', '0008_delete_returnvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp2', models.IntegerField(null=True)),
                ('temp3', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
